### ISSUE TITLE
Videos not loading..

### ISSUE THREAD

**Issue by veronicafrost** [besuper/TwitchNoSub#23]
I tried Edge, Chrome and Brave but the videos are not loading.

**Comment by besuper** [comment]
Hi, can you provide more information? Like a screen of a twitch VOD, logs/errors in the console. Tell me what happens when you go on a VOD, ...

**Comment by veronicafrost** [comment]
![error](https://user-images.githubusercontent.com/112399020/187320114-18befaef-5b8a-4a55-a192-9de3631524a3.jpg)

It only displays this page. 

<img width="618" alt="image" src="https://user-images.githubusercontent.com/112399020/187320618-c2dea336-5bb2-4180-90d3-bdcde0bf8a1c.png">

this is the error showing in edge. Maybe i am doing something wrong. Your help will be very much appreciated! thanks!

**Comment by besuper** [comment]
Thanks for the additional information! This issue should be fixed with the last commit

**Comment by veronicafrost** [comment]
Thank you for your response! Do i need to do anything from my side or should it work now automatically?

**Comment by besuper** [comment]
You need to download the last version of the extension from the code button 
![image](https://user-images.githubusercontent.com/16976439/187440588-d3c1ad5a-7162-48a7-ae86-786457d6c6e4.png)
and replace the old version. When it's done you just need to refresh the extension on chrome and everything should work.

**Comment by veronicafrost** [comment]
![error](https://user-images.githubusercontent.com/112399020/187445380-5bd84f34-830f-4808-a6e5-840ee93fbe81.jpg)

I reuploaded the whole thing but it is still showing this error! Sorry for being a bother

**Comment by besuper** [comment]
This error should not be a problem. It just means the player failed to autoplay. Does the VOD playback work or is there still an error?

**Comment by TugaPowerROM** [comment]
@besuper getting also problem with firefox and latest release.

![imagem](https://user-images.githubusercontent.com/9769460/187736513-2d43b7b3-4eda-4a8f-9c98-3919654b5ab9.png)

**Comment by besuper** [comment]
> @besuper getting also problem with firefox and latest release.
> 
> ![imagem](https://user-images.githubusercontent.com/9769460/187736513-2d43b7b3-4eda-4a8f-9c98-3919654b5ab9.png)

Does this happen on every VODs? Can you send me the VOD link please?

**Comment by TugaPowerROM** [comment]
Its happening with any vod, with older release it worked.

Example: https://www.twitch.tv/videos/1577258919

**Comment by besuper** [comment]
> Its happening with any vod, with older release it worked.
> 
> Example: https://www.twitch.tv/videos/1577258919

This comes from the muted segment from the start of the VOD. The error is from [http-streaming](https://github.com/videojs/http-streaming) lib, it can't read the muted segment and stop the current playlist because it falls into a stalled download. An old version of the lib works and reads the segment correctly. The problem is it could create other issues and it will not be stable. So I don't know what is the best option if I downgrade the lib version or if I fast forward and skip the muted segment.

**Comment by veronicafrost** [comment]
> This error should not be a problem. It just means the player failed to autoplay. Does the VOD playback work or is there still an error?

It is still not working. I just unpacked the extension and uploaded it, maybe i am missing some other step?

**Comment by besuper** [comment]
The issue is probably fixed in version 0.6. @veronicafrost can you retry please
